export const defaultFonts = [
    'Arial',
    'Verdana',
    'Helvetica',
    'Tahoma',
    'Trebuchet MS',
    'Georgia',
    'Times New Roman',
    'Courier New',
    'Lucida Console',
    'Impact',
    'Comic Sans MS',
    'Garamond',
    'Palatino',
    'Bookman',
    'Arial Black',
    'Candara',
    'Segoe UI',
    'Roboto',
    'Open Sans',
    'Montserrat',
];
